# Usa una imagen oficial de Node
FROM node:22-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY Frontend/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY Frontend/ .

# Expone el puerto en el que Vite corre por defecto
EXPOSE 5173

# Comando para iniciar la app en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]
